### ISSUE TITLE
Page not Found

### ISSUE THREAD

**Issue by WaterGuy2028** [nano-proxy/nano#8]
Whenever I try to search something up, it says page not found
![Screenshot 2024-10-30 1 58 46 PM](https://github.com/user-attachments/assets/776b7c1c-e9ff-45f0-a326-8a7a163cc5c0)

**Comment by Nebelung-Dev** [comment]
Bug with the demo mode. Works (not the proxy but the demo page) now
![image](https://github.com/user-attachments/assets/6702f05b-93e3-46c2-ae34-a982f11c065a)
